shell format

diff --git a/.local/bin/caddyserve b/.local/bin/caddyserve
--- a/.local/bin/caddyserve
+++ b/.local/bin/caddyserve
@@ -10,18 +10,18 @@ default_port="8080"
 default_caddy_version="2-alpine"
 
 log() {
-  echo >&2 "$*"
+    echo >&2 "$*"
 }
 
 finally() {
-  trap - SIGINT SIGTERM ERR EXIT
-  if [[ -f $config ]]; then rm -f "${config}"; fi
-  log "Bye :)"
+    trap - SIGINT SIGTERM ERR EXIT
+    if [[ -f $config ]]; then rm -f "${config}"; fi
+    log "Bye :)"
 }
 
 usage() {
-  set +o xtrace
-  log "Usage: $(basename "${BASH_SOURCE[0]}") [-p=<port>] [-c=<version>] [-v] [-h] [--] [<path>]
+    set +o xtrace
+    log "Usage: $(basename "${BASH_SOURCE[0]}") [-p=<port>] [-c=<version>] [-v] [-h] [--] [<path>]
 Specified path will be served with auto indexing Caddy file server.
 Options:
   -p        Listen on port (default ${default_port})
@@ -31,25 +31,25 @@ Options:
 }
 
 check_dependency() {
-  if ! command -v "$1" >/dev/null 2>&1; then
-    log "Error: Missing dependency: $1"
-    exit 1
-  fi
+    if ! command -v "$1" > /dev/null 2>&1; then
+        log "Error: Missing dependency: $1"
+        exit 1
+    fi
 }
 
 sanitize() {
-  echo "$*" | inline-detox
+    echo "$*" | inline-detox
 }
 
 find_engine() {
-  if   command -v docker >/dev/null 2>&1; then
-    echo "docker"
-  elif command -v podman >/dev/null 2>&1; then
-    echo "podman"
-  else
-    log "Error: No compatible container engine found!"
-    exit 1
-  fi
+    if command -v docker > /dev/null 2>&1; then
+        echo "docker"
+    elif command -v podman > /dev/null 2>&1; then
+        echo "podman"
+    else
+        log "Error: No compatible container engine found!"
+        exit 1
+    fi
 }
 
 # ENTRYPOINT
@@ -59,38 +59,41 @@ check_dependency detox
 port="${default_port}"
 caddy_version="${default_caddy_version}"
 while getopts p:c:vh? opt; do
-  case $opt in
-  p) port="$OPTARG" ;;
-  c) caddy_version="$OPTARG" ;;
-  v) set -o xtrace ;;
-  h | \? | *) usage ; exit ;;
-  esac
+    case $opt in
+        p) port="$OPTARG" ;;
+        c) caddy_version="$OPTARG" ;;
+        v) set -o xtrace ;;
+        h | \? | *)
+            usage
+            exit
+            ;;
+    esac
 done
 shift $((OPTIND - 1))
 
 config=$(mktemp)
 {
-  echo "{"
-  echo "    debug"
-  echo "}"
-  echo ":80 {"
-  echo "    root * /var/www"
-  echo "    encode gzip"
-  echo "    file_server browse"
-  echo "}"
-} >"${config}"
+    echo "{"
+    echo "    debug"
+    echo "}"
+    echo ":80 {"
+    echo "    root * /var/www"
+    echo "    encode gzip"
+    echo "    file_server browse"
+    echo "}"
+} > "${config}"
 
 path=$(realpath "${1:-$PWD}")
 
 log "Serving ${path} on http://localhost:${port}"
 
 engine="$(find_engine)"
-$(${engine} --version >/dev/null 2>&1 || echo "sudo") "${engine}" run \
-  --name "caddy-$(sanitize "${path}")" \
-  --interactive \
-  --tty \
-  --rm \
-  --publish "${port}:80" \
-  --volume  "${path}:/var/www":ro \
-  --volume  "${config}:/etc/caddy/Caddyfile":ro \
-  "caddy:${caddy_version}"
+$(${engine} --version > /dev/null 2>&1 || echo "sudo") "${engine}" run \
+    --name "caddy-$(sanitize "${path}")" \
+    --interactive \
+    --tty \
+    --rm \
+    --publish "${port}:80" \
+    --volume "${path}:/var/www":ro \
+    --volume "${config}:/etc/caddy/Caddyfile":ro \
+    "caddy:${caddy_version}"
diff --git a/.local/bin/template b/.local/bin/template
--- a/.local/bin/template
+++ b/.local/bin/template
@@ -9,19 +9,19 @@ set -o errtrace
 trap finally SIGINT SIGTERM ERR EXIT
 
 log() {
-  echo >&2 "$*"
+    echo >&2 "$*"
 }
 
 finally() {
-  trap - SIGINT SIGTERM ERR EXIT
-  log "Bye ;)"
+    trap - SIGINT SIGTERM ERR EXIT
+    log "Bye ;)"
 }
 
 usage() {
-  set +o xtrace
-  local script_name
-  script_name="$(basename "${BASH_SOURCE[0]}")"
-  log "Usage: ${script_name} -a=<text> [-b=<text>] [-s=<text>] [-v] [-h] [--] [<arg>...]
+    set +o xtrace
+    local script_name
+    script_name="$(basename "${BASH_SOURCE[0]}")"
+    log "Usage: ${script_name} -a=<text> [-b=<text>] [-s=<text>] [-v] [-h] [--] [<arg>...]
 Fancy tool to concat some strings.
 Reads inputs either from args or from stdin if no args are present.
 Options:
@@ -33,23 +33,23 @@ Options:
 }
 
 read_stdin() {
-  if [[ -p /dev/stdin ]]; then
-    local line
-    while IFS= read -r line; do
-      echo "${line}"
-    done
-  fi
+    if [[ -p /dev/stdin ]]; then
+        local line
+        while IFS= read -r line; do
+            echo "${line}"
+        done
+    fi
 }
 
 check_dependency() {
-  if ! command -v "$1" >/dev/null 2>&1; then
-    log "Error: Missing dependency: $1"
-    exit 1
-  fi
+    if ! command -v "$1" > /dev/null 2>&1; then
+        log "Error: Missing dependency: $1"
+        exit 1
+    fi
 }
 
 sanitize() {
-  echo "$*" | inline-detox
+    echo "$*" | inline-detox
 }
 
 # ENTRYPOINT
@@ -62,20 +62,23 @@ check_dependency jq
 unset a b s
 s="_"
 while getopts a:b:s:vh? opt; do
-  case $opt in
-  a) a="$OPTARG" ;;
-  b) b="$OPTARG" ;;
-  s) s=$(sanitize "$OPTARG") ;;
-  v) set -o xtrace ;;
-  h | \? | *) usage ; exit ;;
-  esac
+    case $opt in
+        a) a="$OPTARG" ;;
+        b) b="$OPTARG" ;;
+        s) s=$(sanitize "$OPTARG") ;;
+        v) set -o xtrace ;;
+        h | \? | *)
+            usage
+            exit
+            ;;
+    esac
 done
 shift $((OPTIND - 1))
 
 # check required options
 if [[ -z $a ]]; then
-  log "Error: Missing option: -a"
-  exit 1
+    log "Error: Missing option: -a"
+    exit 1
 fi
 
 # print to stderr
